### ISSUE TITLE
echo the recaptcha into my form

### ISSUE THREAD

**Issue by karev** [jasonlewis/laravel-recaptcha#1]
hello jason i want to know how to echo the recaptcha verification image into my form ?

**Comment by ramirors** [comment]
JS, 

http://paste.laravel.com/jKP

**Comment by udemethegrtman** [comment]
Hi jason lewis i tried to install the recaptcha but this is the error i got...  
$ php artisan bundle:install recaptcha

  [InvalidArgumentException]  
  There are no commands defined in the "bundle" namespace.

**Comment by jasonlewis** [comment]
This is a VERY old Laravel 3 bundle my friend. It won't work on Laravel 4+.

**Comment by udemethegrtman** [comment]
wow :-}  so will there be no updates cause... it looks official for me to use...
